### ISSUE TITLE
Support for OracleCommand#BindByName property

### ISSUE THREAD

**Issue by lobin-z0x50** [ttakahari/AdoNetProfiler#1]
初めまして。AdoNetProfiler と Glimpseとの連携がとてもいいですね。
Oracle + Dapper の構成において、`OracleCommand#BindByName` に相当するプロパティがないため、名前付きパラメータを使用したときに正しく動作しない現象がありました。
例えば MiniProfiler では、以下のようにリフレクションを使って `BindByName` プロパティに対応しているようです。
https://github.com/MiniProfiler/dotnet/blob/0e418c66eebbcf4ea0f2e96413d2e5932abd4a88/src/MiniProfiler.Shared/Data/ProfiledDbCommand.cs#L29

`AdoNetProfilerDbCommand` でも同様に `BindByName` プロパティの対応を検討して頂けませんでしょうか。

**Comment by ttakahari** [comment]
@lobin-z0x50 
ご報告頂きありがとうございます。

なるほど、Oracleではこのプロパティがないと名前でバインドされないんですね。
対応しますので少々お時間を下さい。

もし近々で対応が必要であれば以下の方法もご検討頂ければと思います。
```csharp
var oracleCommand = ((AdoNetProfilerDbCommand)command).WrappedCommand as OracleCommand;

if (oracleCommand != null)
{
    oracleCommand.BindByName = true;
}
```

**Comment by lobin-z0x50** [comment]
@ttakahari ありがとうございます。よろしくお願いします。
回避策のご提示もありがとうございます。ですが、Dapper と EntityFramework を使用した既存のプロダクトに適用しようとしているので、Command オブジェクトを意識したコーディングになっておらず、どうしたもんかと頭を悩ませております。。。

**Comment by ttakahari** [comment]
@lobin-z0x50 
本件対応してv0.4.0としてNuGetにリリースしました。
ご確認お願い致します。

**Comment by lobin-z0x50** [comment]
当方のOracle+Dapper環境でも正しく動作することが確認できました。
ありがとうございました！
