### ISSUE TITLE
Cache conflict in AdoNetProfilerDbCommand#GetBindByNameGetAction()

### ISSUE THREAD

**Issue by lobin-z0x50** [ttakahari/AdoNetProfiler#3]
`AdoNetProfilerDbCommand#GetBindByNameGetAction()` にて例外が発生するケースが見つかりました。

![image](https://user-images.githubusercontent.com/11419109/34711129-7d55ca22-f561-11e7-8ece-e3fe3e0ed3ea.png)

以下の箇所の `lock` で待機が発生した場合、上の if をすでに通りすぎているため、複数回連続で cache に Add() しにいって例外発生しているようです。
https://github.com/ttakahari/AdoNetProfiler/blob/master/src/AdoNetProfiler/AdoNetProfilerDbCommand.cs#L272

**Comment by ttakahari** [comment]
@lobin-z0x50 
ご報告頂きありがとうございます。
こちらの不具合によりご迷惑おかけして申し訳ございません。

私の環境でも再現できたため修正し、v0.4.1としてリリースしました。
ご確認お願い致します。

**Comment by lobin-z0x50** [comment]
確認できました！ありがとうございました！
